# Generated by Django 3.0.7 on 2020-06-06 03:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('product_url', models.TextField()),
                ('img_url', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.Offer')),
                ('products', models.ManyToManyField(to='app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('offer_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Offer')),
                ('gender', models.CharField(choices=[('남자', '남자'), ('여자', '여자')], max_length=2)),
                ('age', models.IntegerField()),
                ('taste', models.CharField(choices=[('실용', '실용적'), ('고급', '고급스러운')], max_length=2)),
                ('temperament', models.CharField(choices=[('외향적', '외향적'), ('내향적', '내향적')], max_length=3)),
                ('purpose', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('result_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.Result')),
                ('satisfy', models.IntegerField()),
                ('product_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app.Product')),
                ('user_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
